### ISSUE TITLE
Centerpoint detection tracking result

### ISSUE THREAD

**Issue by derekray311511** [megvii-research/MCTrack#1]
Hi! Thanks for sharing this awesome work!

When I tried to reproduce the tracking results (0.740 AMOTA on nuscenes val) using centerpoint detection provided from the author of centerpoint, I can only got 0.727 AMOTA on nuscenes validation dataset. May I ask which detection file did you use before converting it to the baseVersion data format? Many thanks!

The centerpoint detection I used:
centerpoint_voxel_1440: mAP: 59.6, NDS: 66.8

**Comment by coderookieqi** [comment]
> Hi! Thanks for sharing this awesome work!
> 
> When I tried to reproduce the tracking results (0.740 AMOTA on nuscenes val) using centerpoint detection provided from the author of centerpoint, I can only got 0.727 AMOTA on nuscenes validation dataset. May I ask which detection file did you use before converting it to the baseVersion data format? Many thanks!
> 
> The centerpoint detection I used: centerpoint_voxel_1440: mAP: 59.6, NDS: 66.8

Hello, I am honored that you are interested in our work. The results of centerpoint's nuscenes validation set we used are already available on both Baidu and Google drives. The web disk link is in readme. It can be downloaded and used.

**Comment by derekray311511** [comment]
Thanks! Saw it 😄

**Comment by Xuanrrr** [comment]
Could you let me know the detection metrics used for CenterPoint, such as mAP and NDS? I want to try running the entire "track by detecting" pipeline myself. Thanks a lot!
