### ISSUE TITLE
关于load_image和load_point

### ISSUE THREAD

**Issue by houshuaipeng** [megvii-research/MCTrack#4]
作者您好：
       我在准备好正确的非空的detector数据后，运行main.py的时候，发现其中有两个参数：load_image和load_point虽然指定了，但是并没有用到，请问这两个参数是用来做什么的呢？后续有更新main.py的计划吗？

盼复

**Comment by wangxiyang2022** [comment]
您好：
这两个参数分别为加载原始的图像和点云，用于跟踪结果的可视化。目前release的版本没有放可视化代码故这两个参数可以忽略，如果需要可视化，可以参考[repo](https://github.com/hailanyi/3D-Detection-Tracking-Viewer).
