### ISSUE TITLE
我在使用nusences数据集的val.json文件中并不包含frame_id，timestamp，transform_matrix等信息

### ISSUE THREAD

**Issue by ZZC-CN** [megvii-research/MCTrack#8]
代码是使用的class BaseVersionTrackingDataset，调试结果如图，是我哪里步骤做错了么？
![2a84d586-0bea-4835-8b45-1019e8eeb9f3](https://github.com/user-attachments/assets/c402d241-70e3-4ed7-b0cf-5832082e2d39)

**Comment by coderookieqi** [comment]
请问一下你是在哪个步骤出现了这个错误呢？nuscenes验证集的检测结果使用的是我们网盘中的centerpoint的val.json吗？

**Comment by ZZC-CN** [comment]
> 请问一下你是在哪个步骤出现了这个错误呢？nuscenes验证集的检测结果使用的是我们网盘中的centerpoint的val.json吗？

![图片](https://github.com/user-attachments/assets/e5af3348-4c31-4aa1-9f14-fd0838d88373)
主要是这部分的代码

**Comment by coderookieqi** [comment]
需要首先把原始的检测结果格式转换成为我们框架适用的basevision的格式，运行：
python preprocess/convert2baseversion.py --dataset nuscenes
使用转换好的检测结果作为跟踪系统的输入。
